(function(g,h,k,l,f){g[h]=g[h]||{};for(g[h].q=g[h].q||[];f<l.length;)k(l[f++],g[h])})(window,"extole",function(g,h){h[g]=h[g]||function(){h.q.push([g,arguments])}},["log"],0);
extole.define||function(){function g(a){a=f(a);return w[a]}function h(a,b){extole.log("error","[REQUIRE] "+a,b)}function k(a,b){if(a.length)for(var d=0;d<a.length;d++)b(a[d],d);else for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b(a[d],d)}function l(a,b){var d=[];k(a,function(a,m){d[m]=b(a,m)});return d}function f(a){return"string"!==typeof a?a:/origin-\d/.test(a)?a.substring(a.indexOf("type=")).replace(/version=\d+:/,""):a}function n(a){var b=a.split("/").slice(-1)[0],d=b.length;k(b.toLowerCase(),
function(a){d+=" abcdefghijklmnopqrstuvwxyz1234567890-_.".indexOf(a)});return a.replace("origin","origin-"+d%8)}function c(a){var b=/^extole-creatives:/.test(a),d=/^extole-media:/.test(a),m=/^core-root:\/\//.test(a),e=/^extole-assets:/.test(a),q=/origin\./.test(a),t=/^http:/.test(a),f=/^https:/.test(a);return b?(a=a.slice(17),c("extole-assets:/core-modules/"+a)):e?(a=a.slice(14),c("extole-media:/assets/"+a)):d?(a=a.slice(13),a=extole.CORE_ROOT+a,c(a)):m?(a=a.slice(12),a=extole.CORE_ROOT+a,c(a)):q?
(a=n(a),a+="?site="+window.location.hostname,c(a)):t?(a=a.slice(5),c(a)):f?(a=a.slice(6),c(a)):a}function e(){}function b(){var a="undefined"!==typeof window.opera&&"[object Opera]"===window.opera.toString(),b=document.createElement("script");this.useInteractive=b.attachEvent&&!(b.attachEvent.toString&&0>b.attachEvent.toString().indexOf("[native code"))&&!a}function a(){k(w,function(a){a._fetched?a._defined||a.define():a.fetch()})}function d(a,b,d,m,c){if("$config"!=a){var q=g(a),p=q||new e;q||(q=
f(a),w[q]=p);a&&b&&(p._fetched=!0);p.start=p.start||(new Date).getTime();p.url=p.url||a;p.dependencies=p.dependencies||b;p.config=p.config||m;p.definedCallback=p.definedCallback||d;p.isRequire=p.isRequire||c}}function m(a,b,d,m){a instanceof Array&&(m=d,d=b,b=a,a=void 0);v.addDefine({url:a,dependencies:b,definedCallback:d,config:m})}function q(){u++;return"anonymous_"+u}var w={};e.prototype={getUnresolvedDependencies:function(){var a=[];k(this.dependencies,function(b){"$config"!=b&&(b=g(b),(!b||b&&
!b._defined)&&a.push(b))});return a},getDependencies:function(){var a=this,b=[];k(a.dependencies,function(d){d="$config"==d?a.config||null:g(d).definition||null;b.push(d)});return b},define:function(){function b(b){d.definedCallback=void 0;d.definition=b;d.end=(new Date).getTime();d.timeToDefine=d.end-d.start;d._defining=!1;d._defined=!0;setTimeout(a,1)}var d=this;d.defineStartTime=d.defineStartTime||(new Date).getTime();if(!d._defining&&!d._defined&&d.dependencies)if(d._defining=!0,0<d.getUnresolvedDependencies().length)d._defining=
!1;else{var m=d.getDependencies(),c={isAsync:!1,async:function(){d.isAsync=!0;c.isAsync=d.isAsync;return function(a){b(a)}}};(function(){if(d.definedCallback){var a=d.definedCallback;a=a&&a.apply(c,m);c.isAsync||b(a)}else b(!0)})()}},fetch:function(){var a=this;a._fetching||a._fetched||(a.url?(a._fetching=!0,a.startFetchTime=(new Date).getTime(),v.loadModule(a.url,function(){a._fetching=!1;a.endFetchTime=(new Date).getTime();a.timeToFetch=a.endFetchTime-a.startFetchTime;a._fetched=!0;a.define()})):
h("Tried to fetch a module without a url - dependencies: "+a.dependencies+" definedCallback: "+(a.definedCallback?"exists":"null")+" config: "+a.config))}};b.prototype={defineQueue:[],interactiveScript:null,currentlyAddingScript:null,getInteractiveScript:function(){if(v.interactiveScript&&"interactive"==v.interactiveScript.readyState)return v.interactiveScript;for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b,d=a.length-1;0<=d;d--){var m=this.getScriptDataUrl(a[d]);
a[d]&&"interactive"==a[d].readyState&&m&&(b=a[d])}return b},scriptUrlAttributeName:"data-extole-require-url",getScriptDataUrl:function(a){return a.getAttribute(this.scriptUrlAttributeName)},setScriptDataUrl:function(a,b){a.setAttribute(this.scriptUrlAttributeName,b)},attachOnLoad:function(a,b){function d(e){var q=a.readyState;if(m&&"interactive"==q)this.interactiveScript=a;else if("load"===e.type||c.test(q))m?a.detachEvent("onreadystatechange",d):a.removeEventListener("load",d,!1),b(e)}b=b||function(){};
var m=this.useInteractive,c="PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/;m?a.attachEvent("onreadystatechange",d):a.addEventListener("load",d,!1)},defineTimeout:null,addDefine:function(a){if(a.url)a.url=c(a.url);else{var b=this.currentlyAddingScript||this.getInteractiveScript();this.useInteractive&&b&&(b=this.getScriptDataUrl(b),a.url=b,this.interactiveScript=null)}a.dependencies=l(a.dependencies,c);this.useInteractive&&!a.url&&h("defines should not be missing a url in ie.");
this.defineQueue.push(a);this.defineTimeout&&clearTimeout(this.defineTimeout);var d=this;this.defineTimeout=setTimeout(function(){d.intakeDefines()},1)},intakeTimeout:null,intakeDefines:function(){for(var b=[],m;m=this.defineQueue.shift();){var c=[];k(m.dependencies,function(a){a&&c.push(a)});m.url&&g(m.url);m.url||b.push("deps "+m.dependencies);k(c,function(a){d(a)});d(m.url,c,m.definedCallback,m.config,m.isRequire)}this.intakeTimeout&&clearTimeout(this.intakeTimeout);this.intakeTimeout=setTimeout(a,
1)},loadModule:function(a,b){var d=document.createElement("script");d.async=!0;d.crossOrigin="anonymous";this.setScriptDataUrl(d,a);var m=this;this.attachOnLoad(d,function(){clearTimeout(c);if(!m.useInteractive){for(var d,e=m.defineQueue.length-1;0<=e;e--)m.defineQueue[e].url||(d&&h("Multiple anonymous modules loaded in one script - "+a),d=m.defineQueue[e]);d&&(d.url=a)}m.intakeDefines();b&&b(null)});d.src=a;var c=setTimeout(function(){extole.log("warn","[REQUIRE] Module did not load within 2000ms: ",
{moduleUrl:a})},2E3);this.currentlyAddingScript=d;var e=document.getElementsByTagName("head")[0]||document.head;e?e.appendChild(d):extole.log("warn","[REQUIRE] <head> element not found on trying to load "+a,void 0);this.currentlyAddingScript=void 0}};var v=new b;m.getModule=function(a){return g(a)};var u=0;extole.define=m;extole.require=function(a,b){v.addDefine({url:q(),dependencies:a,definedCallback:b,isRequire:!0})};extole.define("extole-require",[],function(){return{resolveUrl:c}});setTimeout(function(){var a=
!1,b=[];k(w,function(d){d._defined||(a=!0);b.push({defineStartTime:d.defineStartTime,dependencies:d.dependencies,end:d.end,start:d.start,isRequire:d.isRequire,timeToDefine:d.timeToDefine,url:d.url,_defined:d._defined,_defining:d._defining,_fetched:d._fetched})});a&&extole.DUMP_REQUIRE_MODULES_ON_ERROR&&extole.log("error","After 7000ms there are unresolved extole-require modules.  ###"+JSON.stringify(b)+"###")},7E3)}();(function(){})();
extole.define("extole-uri-parser",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js"],function(g,h){var k=/^extole_(?!zone)/,l=/^extole_zone_/;return new function(){function f(e){var b={};e=e||c;g.each(e,function(a,d){k.test(d)&&(d=d.replace(k,""),b[d]=a)});return b}function n(){var c,b,a={};this.withName=function(a){c=a;return this};this.withElementId=function(a){b=
a;return this};this.withData=function(b,m){a[b]=m;return this};this.build=function(){var d={};c&&(d.name=c);b&&(d.elementId=b);a&&(d.data=a);return d}}var c=h.deserialize(location.search);this.parseUriZoneDefinition=function(e){var b=new n,a;e=e||c;var d=f(e);g.each(d,function(a,d){b.withData(d,a)});g.each(e,function(d,c){l.test(c)&&(c=c.replace(l,""),"name"===c?(a=!0,b.withName(d)):"element_id"===c?b.withElementId(d):b.withData(c,d))});return a?b.build():null};this.parseGlobalZoneParameters=f}});
(function(g,h,k,l,f){g[h]=g[h]||{};for(g[h].q=g[h].q||[];f<l.length;)k(l[f++],g[h])})(window,"extole",function(g,h){h[g]=h[g]||function(){h.q.push([g,arguments])}},["createZone","log"],0);
(function(){var g=[{name:"Zoom Referral Program",programDomain:"zoom.extole.io",sitePatterns:["zoom.extole.io","zoomdev.us","*.zoomdev.us","zoomext.us","*.zoomext.us"],siteRegexPatterns:["zoom\\.extole\\.io\\.?$","zoomdev\\.us\\.?$",".*\\.zoomdev\\.us\\.?$","zoomext\\.us\\.?$",".*\\.zoomext\\.us\\.?$"]},{name:"Branded Program Domain",programDomain:"rewards.zoom.us",sitePatterns:["rewards.zoom.us","zoom.us","*.zoom.us","go.zoom.us","*.go.zoom.us"],siteRegexPatterns:["rewards\\.zoom\\.us\\.?$","zoom\\.us\\.?$",
".*\\.zoom\\.us\\.?$","go\\.zoom\\.us\\.?$",".*\\.go\\.zoom\\.us\\.?$"]}];extole.CORE_ROOT="https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139";extole.CORE_CONFIG={backendTargetingEnabled:!0,isZonePostEnabled:!1,isCookieConsentEnabled:!1,isJsCreativeRespondsWithHtmlEnabled:!1,isGlobalZoneParametersEnabled:!0,zonePostEnabled:!1,cookieConsentEnabled:!1};extole.CLIENT_ID="841133454";extole.BUILD_DATE="1663788736516";extole.VERSION="6.0";extole.IS_DEBUG_ENABLED=extole.debug||/[?&]extole_debug=true(&|$)/.test(location.search);
extole.PROGRAM=function(){function h(b,a){b=Error.call(this,b);this.name="ExtoleError";this.message=b.message;this.stack=b.stack;this.code=a}function k(b,a){if(b.length)for(var d=0;d<b.length;d++)a(b[d],d);else for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&a(b[d],d)}function l(b,a){var d=[];k(b,function(b){(b=a(b))&&(d[d.length]=b)});return d}function f(b,a){a=a||[];var d=!1;k(a,function(a){(new RegExp(a)).test(b)&&(d=!0)});return d}function n(){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js",
"https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ajax.js"],function(b,a){var d=extole.CORE_ROOT;b=d.replace(/(https?:\/\/[a-z-\.]+)(\/.*)/,"$1")+"/_extole_core.gif"+b.serialize({core_root:d,referer:window.location.hostname});a({url:b})})}h.prototype=Error();h.prototype.constructor=h;var c=function(b){var a=window.location.hostname;return l(b,function(b){if(f(a,b.siteRegexPatterns))return b})}(g),e=c[0];if(!e)throw n(),new h("No program domain is configured for hostname: "+
window.location.hostname+" unable to use Extole API","site_configuration_error");1<c.length&&extole.log("warn","Multiple programs matched hostname: "+window.location.hostname+" programs: "+JSON.stringify(c));return e}();extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js","create-zone-executor"],function(h,g,l){function f(){function b(b){var d=b[0];"function"===
typeof a[d]?(a[d].apply(null,b[1]),extole.q.history.push({name:b[0],args:b[1],timestamp:Date.now(),stack:Error().stack})):g.warn("Unable to execute method: "+d+", it is not implemented.")}var a={log:function(){var a=Array.prototype.slice.call(arguments),b=a[0];"function"===typeof g[b]&&g[b].apply(null,a.slice(1))},createZone:l.initiateExecution};for(extole.q.history=[];extole.q.length;)b(extole.q.shift());extole.q.push=b}function k(){extole.require(["extole-uri-parser"],function(b){var a=h.deserialize(location.search);
(b=b.parseUriZoneDefinition(a))&&extole.createZone(b)})}function c(){if("function"===typeof window.onerror)var b=window.onerror;window.onerror=function(a,d,c,e,f){if(b)try{b(a,d,c,e,f)}catch(t){}d=d||window.location.href||"no_source_or_location.href";f=f&&f.stack?f.stack:"no_error.stack";var m=[],q=JSON.stringify({MESSAGE:a,SOURCE:d,LINE_NUMBER:c,COLUMN_NUMBER:e,STACK_TRACE:f},function(a,b){if(null!==b&&"object"===typeof b){if(0<=m.indexOf(b))return;m.push(b)}return b});c=extole.PROGRAM.programDomain.split(".").join("\\.");
c=new RegExp("^(http|https):\\/\\/("+c+"|(([A-Za-z0-9-]{1,}\\.){1,}|)(xtlo\\.net|extole(\\.com|\\.io)))(?=(\\/|\\?|$))");((f+a).match(/extole/i)||c.test(d))&&extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js"],function(a){a.error("Unhandled exception",JSON.parse(q))})}}function e(){extole._bootstrapped=!0;c();f();k()}extole.bootstrap=e;extole._bootstrapped||e();if("undefined"!==typeof window.extoleAsyncInit)try{window.extoleAsyncInit()}catch(b){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js"],
function(a){a.error("Error executing extended core javascript. Message : "+b.message+" Stack: "+b.stack)})}})})();extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ExtoleError.js",[],function(){function g(g,k,l){g=Error.call(this,g);this.name="ExtoleError";this.message=g.message;this.stack=g.stack;this.code=k;this.data=l}g.prototype=Error();return g.prototype.constructor=g});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ExtoleError.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/type.js"],function(g,h){function k(f,g){var c;if(f.length===Number(f.length))for(c=0;c<f.length;c++){var e=g(f[c],c);if(!1===e)return!1}else for(c in f)if(Object.prototype.hasOwnProperty.call(f,c)&&(e=g(f[c],
c),!1===e))return!1}function l(f){if(!f||"object"!==typeof f&&!h.isPlainFunction(f))f={};for(var g=1;g<arguments.length;g++)if(h.isPlainObject(arguments[g]))for(var c in arguments[g]){var e=arguments[g][c];e!==f&&void 0!==e&&(h.isPlainObject(e)&&h.isPlainObject(f[c])?e=l(f[c],e):h.isArray(e)&&h.isArray(f[c])&&f[c].concat&&(e=f[c].concat(e)),f[c]=e)}return f}k.BREAK=!1;return{each:k,map:function(f,l){function c(a,d){b=[];k(a,function(a,c){b.push(d(a,c))})}function e(a,d){b={};k(a,function(a,c){b[c]=
d(a,c)})}var b;if(h.isArray(f))c(f,l);else if(h.isPlainObject(f))e(f,l);else throw new g(f+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},filter:function(f,l){function c(a,d){b=[];k(a,function(a,c){d(a,c)&&b.push(a)})}function e(a,d){b={};k(a,function(a,c){d(a,c)&&(b[c]=a)})}var b;if(h.isArray(f))c(f,l);else if(h.isPlainObject(f))e(f,l);else throw new g(f+" argument must be type object or array","INVALID_ARGUMENT_EXCEPTION");return b},merge:l,clone:function(f){return JSON.parse(JSON.stringify(f))},
flatten:function(f){function g(e,b){if(h.isPlainObject(e))k(e,function(a,c){var d=b.slice();d.push(c);g(a,d)});else{var a=b.join(".");c[a]=e}}if(!h.isPlainObject(f))return f;var c={};g(f,[]);return c},find:function(f,g){var c;k(f,function(e,b){if(g(e,b))return c=e,k.BREAK});return c},reverse:function(f){var g=[];if(!f||f.length!==Number(f.length))return f;for(var c=f.length-1;0<=c;c--)g.push(f[c]);return g},nashornToJs:function(f){var g=Object.prototype.toString.call(f),c;if("object"!==typeof f||
g.match(/\[object (Object|Array|Null)\]/))return f;if(g.match(/\[object java\.util\.(HashMap|TreeMap|Collections\$UnmodifiableMap)\]/)){var e={};for(c in f)e[c]=f[c]}else if("number"===typeof f.length)e=[],k(f,function(b,a){e[a]=b});else return f;return e},intersection:function(f,g){var c=[];k(f,function(e){0>g.indexOf(e)||0<=c.indexOf(e)||c.push(e)});return c},difference:function(f,g){var c=[];k(f,function(e){0<=g.indexOf(e)||0<=c.indexOf(e)||c.push(e)});return c}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/cookie.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js"],function(g){function h(c){try{return decodeURIComponent(c.replace(f," "))}catch(b){return g.info("** cookie.decode ** Cookie error for: "+c,{error:b,message:b.message,stack:b.stack,cookiePart:c}),""}}function k(e){e=h(e);return 0===e.indexOf('"')?e.slice(1,-1).replace(n,'"').replace(c,"\\"):e}function l(c){if(!c||
!c.toUTCString){var b=new Date;b.setDate(b.getDate()+("number"===typeof c?c:0));return b}return c}var f=/\+/g,n=/\\"/g,c=/\\\\/g;return function(c,b,a){if(void 0!==b)return a=a||{},document.cookie=[encodeURIComponent(c),"=",encodeURIComponent(b),a.expires?"; expires="+l(a.expires).toUTCString():"",a.path?"; path="+a.path:"",a.domain?"; domain="+a.domain:"",a.samesite?"; samesite="+a.samesite:"","; secure"].join("");a:{b=document.cookie?document.cookie.split("; "):[];a=c?null:{};for(var d=0,m=b.length;d<
m;d++){var e=b[d].split("="),f=h(e[0]);if(!c)a[f]=k(e[1]);else if(c===f){c=k(e[1]);break a}}c=a}return c}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/device-type.js",[],function(){function g(g){return h.test(g)}var h=/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|Dolphin|Fennec|(hpw|web)OS|Zune|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Silk-Accelerated|Skyfire|NetFront/i,k=/WebView|\swv|(iPhone|iPod|iPad)(?!.*Safari)|Android.*(wv|.0.0.0)|Linux; U; Android/i;return{isMobile:g,isDesktop:function(l){return!g(l)},isWebview:function(g){return k.test(g)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/dom.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js"],function(g){function h(a,b){return(b||document).querySelectorAll(a)}function k(a,b){return h(a,b)[0]}function l(a,d){function m(){clearTimeout(h);d(f);n.removeListener(f,"load",m)}d=d||function(){};if(b[a]||!a)return d(b[a]),b[a]||null;b[a]=document.createElement("link");var f=b[a];c.setAttribute(f,
"rel","stylesheet");c.setAttribute(f,"href",a);e.append(k("head"),f);n.addListener(f,"load",m);var h=setTimeout(function(){g.warn("Load timeout reached for stylesheet: ",{url:a});m()},5E3);return f}var f={each:function(a,b){var d;if(a.length===Number(a.length))for(d=0;d<a.length;d++){var c=b(a[d],d);if(!1===c)return!1}else for(d in a)if(Object.prototype.hasOwnProperty.call(a,d)&&(c=b(a[d],d),!1===c))return!1},extend:function(){var a,b,c=arguments[0]||{},e=1,f=arguments.length,g=!1,h=this.extend;"boolean"===
typeof c&&(g=c,c=arguments[1]||{},e=2);for("object"===typeof c||this.isFunction(c)||(c={});e<f;e++){var l=arguments[e];if(null!==l)for(a in l){var k=c[a];var r=l[a];c!==r&&(g&&r&&(this.isPlainObject(r)||(b=this.isArray(r)))?(b?(b=!1,k=k&&this.isArray(k)?k:[]):k=k&&this.isPlainObject(k)?k:{},c[a]=h(g,k,r)):void 0!==r&&(c[a]=r))}}return c},isFunction:function(a){return a&&"function"===typeof a&&a.call&&a.apply},isPlainObject:function(a){if("[object Object]"!==String(a)||a.nodeType||a.window&&a.window==
a)return!1;try{if(a.constructor&&!Object.prototype.hasOwnProperty.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(d){return!1}return!0},isArray:function(a){return a instanceof Array}};f.each.BREAK=!1;var n=function(){function a(a,b,d){for(var c=[],e=0;e<h.length;e++){var m=h[e];m.element==a&&m.eventType==b&&m.listener==d&&c.push({index:e,eventListener:m})}return c}function b(a){for(var b=[],d=0;d<h.length;d++){var c=h[d];c.element===a&&b.push(c)}return b}function c(a){this.originalEvent=
a;this.type=a.type;this.keyCode=a.keyCode;this.target=a.srcElement?a.srcElement:a.target}function e(b,d,c){c=a(b,d,c);0>=c.length?g.info("events.remove - Couldn't find exiting event listener for type \""+d+'" listener on element '+b):f.each(c,function(a){var c=a.index;a=a.eventListener;b.removeEventListener?b.removeEventListener(d,a.listenerWrapper,!1):b.detachEvent("on"+d,a.listenerWrapper);h.splice(c,1)})}var h=[];c.prototype={preventDefault:function(){var a=this.originalEvent;a.preventDefault?
a.preventDefault():a.returnValue=!1},stopPropagation:function(){var a=this.originalEvent;a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0}};return{addListener:function(b,d,e){function m(a){f&&(a=window.event);return e.call(b,new c(a))}if(0<a(b,d,e).length)g.warn("events.add - Listener already exists for event "+d+" on element "+b);else{var f=!b.addEventListener;h.push({element:b,eventType:d,listener:e,listenerWrapper:m});b.addEventListener?b.addEventListener(d,m,!1):b.attachEvent("on"+d,m)}},
triggerEvent:function(a,b,d){var c=document.createEvent("Event");d=f.extend({},d);var e=!1===!d.bubbles,m=!0===d.cancelable;delete d.bubbles;delete d.cancelable;c.initEvent(b,e,m);f.extend(c,d);a.dispatchEvent(c)},removeListener:e,clearListeners:function(a){a=b(a);f.each(a,function(a){e(a.element,a.eventType,a.listener)})}}}(),c=function(){function a(a){a=a.className;var b={};if(!a)return b;f.each(a.split(" "),function(a){b[a]=1});return b}function b(a){var b="";f.each(a,function(a,d){b+=" "+d});
return b.slice(1)}return{setAttribute:function(a,b,d){a.setAttribute(b,d);a[b]=d},getAttribute:function(a,b){return a.getAttribute(b)},addClass:function(d,c){var e=a(d);e[c]||(e[c]=1,d.className=b(e))},removeClass:function(d,c){var e=a(d);delete e[c];d.className=b(e)},getClassNames:function(a){return a.className.split(" ")}}}(),e=function(){function a(a){var b=document.createDocumentFragment(),d=document.createElement("div");d.innerHTML=a;f.each(d.childNodes,function(a){1==a.nodeType&&b.appendChild(a)});
return b}function b(a){var b;f.each(a.childNodes,function(a){if(!b&&1==a.nodeType)return b=a,f.each.BREAK});return b}return{prepend:function(d,c){var e=b(d),f=c;"string"===typeof c&&(f=a(c));e?d.insertBefore(f,e):d.appendChild(f)},append:function(b,d){var c=d;"string"===typeof d&&(c=a(d));b.appendChild(c)}}}(),b={};return{addEventListener:n.addListener,removeEventListener:n.removeListener,triggerEvent:n.triggerEvent,clearEventListeners:n.clearListeners,getAttribute:c.getAttribute,setAttribute:c.setAttribute,
addClass:c.addClass,removeClass:c.removeClass,getClassNames:c.getClassNames,prepend:e.prepend,append:e.append,query:h,queryFirst:k,isVisible:function(a,b){return!!(k(a,b)||{}).offsetParent},injectStylesheet:l,injectStylesheets:function(a,b){function d(a){--c||b(e)}b=b||function(){};if(0===a.length)b();else{var c=0,e=[];f.each(a,function(a){c++;setTimeout(function(){e.push(l(a,d))},1)})}},scrollIntoViewIfNeeded:function(a,b){function d(a,b){return{start:a,length:b,end:a+b}}function c(a,d){return!1===
b||d.start<a.end&&a.start<d.end?Math.min(a.start,Math.max(d.start,a.end-d.length)):(a.start+a.end-d.length)/2}function e(a,b){return{x:a,y:b,translate:function(d,c){return e(a+d,b+c)}}}function f(a,b){for(;a;)b=b.translate(a.offsetLeft,a.offsetTop),a=a.offsetParent;return b}var g=f(a,e(0,0)),h=e(a.offsetWidth,a.offsetHeight);a=a.parentNode;for(var l;a instanceof HTMLElement;)l=f(a,e(a.clientLeft,a.clientTop)),a.scrollLeft=c(d(g.x-l.x,h.x),d(a.scrollLeft,a.clientWidth)),a.scrollTop=c(d(g.y-l.y,h.y),
d(a.scrollTop,a.clientHeight)),g=g.translate(-a.scrollLeft,-a.scrollTop),a=a.parentNode}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/event-bus.js",[],function(){function g(){function g(c,e,b,a){if(!b)return!0;if("object"===typeof b){for(var d in b)c[e].apply(c,[d,b[d]].concat(a));return!1}if(n.test(b)){b=b.split(n);d=0;for(var f=b.length;d<f;d++)c[e].apply(c,[b[d]].concat(a));return!1}return!0}function f(c,e){var b,a=-1,d=c.length,f=e[0],g=e[1],h=e[2];switch(e.length){case 0:for(;++a<d;)(b=c[a]).callback.call(b.ctx);break;case 1:for(;++a<
d;)(b=c[a]).callback.call(b.ctx,f);break;case 2:for(;++a<d;)(b=c[a]).callback.call(b.ctx,f,g);break;case 3:for(;++a<d;)(b=c[a]).callback.call(b.ctx,f,g,h);break;default:for(;++a<d;)(b=c[a]).callback.apply(b.ctx,e)}}this._events={};var n=/\s+/;this.on=function(c,e,b){if(!g(this,"on",c,[e,b])||!e)return this;this._events||(this._events={});(this._events[c]||(this._events[c]=[])).push({callback:e,context:b,ctx:b||this});return this};this.off=function(c,e,b){var a,d,f;if(!this._events||!g(this,"off",
c,[e,b]))return this;if(!c&&!e&&!b)return this._events=void 0,this;var h=c?[c]:k.keys(this._events);var l=0;for(d=h.length;l<d;l++)if(c=h[l],a=this._events[c]){var n=[];this._events[c]=n;if(e||b){var u=0;for(f=a.length;u<f;u++){var t=a[u];(e&&e!==t.callback&&e!==t.callback._callback||b&&b!==t.context)&&n.push(t)}}n.length||delete this._events[c]}return this};this.once=function(c,e,b){function a(){var f=h.call(arguments);d.off(c,a,b);e.apply(this,f)}var d=this;this.on(c,a,b);return this};this.trigger=
function(c){if(!this._events)return this;var e=h.call(arguments,1);if(!g(this,"trigger",c,e))return this;var b=this._events[c],a=this._events.all;b&&f(b,e);a&&f(a,arguments);return this}}var h=Array.prototype.slice,k={isPlainObject:function(g){if("[object Object]"!==String(g)||g.nodeType||g.window&&g.window==g)return!1;try{if(g.constructor&&!Object.prototype.hasOwnProperty.call(g.constructor.prototype,"isPrototypeOf"))return!1}catch(f){return!1}return!0},keys:function(g){if(!this.isPlainObject(g))return[];
var f=[],h;for(h in g)Object.prototype.hasOwnProperty.call(g,h)&&f.push(h);return f},_idCounter:0,uniqueId:function(g){var f=String(++this._idCounter);return g?g+f:f}};return{create:function(){return new g}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js",[],function(){function g(a,b,d){f||(f=b.getGlobalServices().getJsLoggingService());f[a](d)}function h(f,g,h){var m=String(extole.CORE_ROOT).match(/coreAssetsVersion=(\d+)/);h=h||{};h.pageId=c;h.referer=e;h.coreAssetsVersion=m&&m[1];try{var q=[g||"no message","START_JSON",JSON.stringify(h),"END_JSON"].join(" ")}catch(t){l("Failed to stringify log's json data",{exception:t});return}if(!extole.LOG_EXCLUDE_REGEX||
!q.match(extole.LOG_EXCLUDE_REGEX)){d[q]=++d[q]||1;if(b[f]>=b[extole.LOG_LEVEL_CONSOLE]&&(g=f+" "+q,window.console))if(window.console[f.toLowerCase()])window.console[f.toLowerCase()](g);else window.console.log(g);b[f]>=b[extole.LOG_LEVEL_REMOTE]&&(g=d[q],a[g]&&k(f,q+(1<g?" log count: "+g:"")))}}function k(a,b){extole.require(["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/api.js"],function(d){d.post("/api/v4/debug/logs",{level:a,message:b},null,{headers:{"Content-Type":"application/x-www-form-urlencoded"}})})}
function l(a,b){h("ERROR",a,b)}var f;if("undefined"===typeof window)return{debug:function(a,b){g("debug",a,b)},info:function(a,b){g("info",a,b)},warn:function(a,b){g("warn",a,b)},error:function(a,b){g("error",a,b)},LOGGING_ENDPOINT:"/api/v4/debug/logs"};var n=extole.IS_DEBUG_ENABLED?"DEBUG":"OFF",c=String((new Date).getTime()),e=window.location.href,b={DEBUG:0,INFO:1,WARN:2,ERROR:3,OFF:4},a={1:!0,3:!0,10:!0,30:!0,100:!0,250:!0,500:!0,1E3:!0};extole.LOG_EXCLUDE_REGEX=extole.LOG_EXCLUDE_REGEX||void 0;
extole.LOG_LEVEL_CONSOLE=extole.LOG_LEVEL_CONSOLE||n;extole.LOG_LEVEL_REMOTE=extole.LOG_LEVEL_REMOTE||"WARN";var d={};return{debug:function(a,b){h("DEBUG",a,b)},info:function(a,b){h("INFO",a,b)},warn:function(a,b){h("WARN",a,b)},error:l,LOGGING_ENDPOINT:"/api/v4/debug/logs"}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/Timer.js",[],function(){return function(){var g=this,h;this.start=function(){if(h)throw Error("Timer.start has already been called");h=new Date;return g};this.getElapsedTime=function(){if(!h)throw Error("Timer has not been started");return new Date-h}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/type.js",[],function(){function g(g,l){return function(f){return h(g,f,l)}}function h(g,h,f){f=f||{};g=Object.prototype.toString.call(h)==="[object "+g+"]";h=h&&f.construct?h.constructor===f.construct:!0;return(f.negate?!g:g)&&h}return{isPlainObject:g("Object",{construct:Object}),isPlainFunction:g("Function"),isArray:g("Array"),isString:g("String"),isBoolean:g("Boolean"),isNumber:g("Number"),isUndefined:g("Undefined"),
isDefined:g("Undefined",{negate:!0}),isNull:g("Null"),test:h}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js"],function(g){function h(c){var e={};(function m(a,d){for(var c in a){var f=a[c],g=(d?d+".":"")+c;"[object Object]"===Object.prototype.toString.call(f)?m(f,g):"__proto__"!==g&&(e[g]=f)}})(c);return e}function k(c){try{return decodeURIComponent(c)}catch(e){return c}}function l(c,e,b){e=(e||[]).concat("object"===
typeof extole&&extole.PROGRAM?extole.PROGRAM.siteRegexPatterns:[]);b=f(b||location.href);c=f(c);return(/^https?:\/\//.test(c)?g.find(e,function(a){var b=n.exec(c);return(new RegExp(a)).test(b&&b[1])}):1)?c:b}function f(c){return c.replace(/(j|%4A|%6A)(a|%41|%61)(v|%56|%76)(a|%41|%61)(s|%53|%73)(c|%43|%63)(r|%52|%72)(i|%49|%69)(p|%50|%70)(t|%54|%74)(:|%3A)/gi,"")}var n=/^https?:\/\/([^/:?#]+)/i;return{serialize:function(c){var e="",b;for(b in c)e+="&"+encodeURIComponent(b)+"="+encodeURIComponent(String(c[b]));
return e.replace(/^&/,"?")},deserialize:function(c){var e={};if(!c)return e;c=(c.match(/^\?/)?c.slice(1):c).split("&");for(var b=0;b<c.length;b++){var a=c[b].split("="),d=k(a[0]);a=k(a[1]);"__proto__"!==d&&(e[d]=a)}return e},objectToDotNotation:h,dotNotationToObject:function(c){var e={};c=h(c);for(var b in c){for(var a=e,d=b.split("."),f=d.pop();d.length;){var g=d.shift();"__proto__"!==g&&(a[g]=a[g]||{},a=a[g])}"__proto__"!==f&&(a[f]=c[b])}return e},decodeComponent:k,encodeComponent:function(c){return encodeURIComponent(c)},
getSafeRedirectUrl:l,executeSafeRedirect:function(c,e,b){window.location.href=l(c,e,b)}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ajax.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/type.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js"],function(g,h,k,l){function f(b,
a){function d(){4!==b.readyState||x||(x=!0,String(b.status||200).match(/^[23]/)?"function"===typeof z?z.call(b,b.responseText,b):l.warn("'complete' callback must be a function."):A.call(b,b.statusText,b.status),f())}function c(a){x||(x=!0,l.error("Error with url "+p+"= "+n.join(","),e(a)),A.call(b,b.statusText,b.status))}function e(d){return{eventType:d&&d.type||null,options:a,readyState:b.readyState,response:b.response,responseText:b.responseText,responseType:b.responseType,responseURL:b.responseURL,
responseXML:b.responseXML,status:b.status,statusText:b.statusText,timeout:b.timeout,responseHeaders:b.getAllResponseHeaders()}}function f(a){0>p.indexOf(l.LOGGING_ENDPOINT)&&l.debug("ajax request complete",e(a))}var n=Array.prototype.slice.call(arguments),u=a.headers||{},t=a.xhrFields||{},p=a.url||"",r=a.data||"",y=(a.type||"get").toUpperCase(),z=a.complete||function(){},A=a.error||function(){};k.isPlainObject(r)&&("GET"===y?(p+=h.serialize(r),r=null):r=JSON.stringify(r));b.open(y,p,!0);g.merge(b,
t);g.each(u,function(a,d){try{b.setRequestHeader(d,a)}catch(C){l.error("AJAX ERROR: Couldn't set request header "+d+" to "+a)}});var x=!1;b.onload=d;b.onreadystatechange=d;b.onerror=c;b.ontimeout=c;b.onabort=f;b.send(r)}function n(b){g.each(b,function(a,d){"content-type"===d.toLowerCase()&&delete b[d]})}function c(b){b=b||{};var a=!1;for(var d=0;d<e.length;d++){try{a=e[d]()}catch(m){continue}break}f(a,b);return a}var e=[function(){return new XMLHttpRequest},function(){return new ActiveXObject("Msxml2.XMLHTTP")},
function(){return new ActiveXObject("Msxml3.XMLHTTP")},function(){return new ActiveXObject("Microsoft.XMLHTTP")}];c.convertToFormUrlEncoded=function(b,a){function d(a){var b={};g.each(a,function(a,c){c=0<=c.indexOf(".")?'"'+c+'"':c;k.isPlainObject(a)&&(a=d(a));b[c]=a});return b}var c=[];n(b);b["content-type"]="application/x-www-form-urlencoded";a=d(a);a=g.flatten(a);g.each(b,function(a,d){"content-type"!==d.toLowerCase()&&(c.push("::headers."+d+"="+a),delete b[d])});g.each(a,function(a,b){k.isUndefined(a)||
c.push(encodeURIComponent(b)+"="+encodeURIComponent(a))});return c.join("&")};c.convertToMultipartFormData=function(b,a){var d=new FormData;g.each(a,function(a,b){d.append(b,a)});n(b);return d};return c});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/program.js",[],function(){return{getName:function(){return extole.PROGRAM.name},getProgramDomain:function(){return extole.PROGRAM.programDomain},getSitePatterns:function(){return extole.PROGRAM.sitePatterns},getSiteRegexPatterns:function(){return extole.PROGRAM.siteRegexPatterns},getProtocol:function(){return"https://"}}});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/token-store.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/event-bus.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/cookie.js"],
function(g,h,k,l){function f(){function c(){this.get=function(a){return l(a)};this.set=function(a,b,c){extole.COOKIES_DISABLED||l(a,b,{expires:n[c],path:"/",samesite:"strict"})};this.remove=function(a){l(a,"",{expires:-1,path:"/"})}}function e(){(function(){var a="test"+(new Date).getTime();try{localStorage.setItem(a,a),localStorage.removeItem(a)}catch(m){throw Error("Local storage not supported");}})();this.get=function(a){return window.localStorage.getItem(a)};this.set=function(a,b,c){window.localStorage.setItem(a,
b)};this.remove=function(a){window.localStorage.removeItem(a)}}var b=[],a=extole.CORE_CONFIG.isCookieConsentEnabled?"SESSION":"YEAR";b.push(new function(){var a={};this.get=function(b){return a[b]};this.set=function(b,c,d){a[b]=c};this.remove=function(b){delete a[b]}});extole.COOKIES_DISABLED||b.push(new c);if(extole.LOCAL_STORAGE_ENABLED)try{b.push(new e)}catch(d){h.info("Local Storage not supported in current browser")}this.events=k.create();this.get=function(){for(var a,c=0;c<b.length;c++){a=b[c];
var e=a.get("extole_access_token");if("string"===typeof e&&"undefined"!==e&&"null"!==e&&e.length)return a.get("extole_access_token")}return null};this.set=function(c,e){var d=this.get();a=e||a;g.each(b,function(b){b.set("extole_access_token",c,a)});d!==c&&this.events.trigger("change:access_token");d&&d!=c&&h.debug("ACCESS_TOKEN_CHANGE - the access token changed from: "+d+", to: "+c)};this.remove=function(){g.each(b,function(a){a.remove("extole_access_token")})}}var n={year:365,YEAR:365,session:null,
SESSION:null};return extole.tokenStore=extole.tokenStore?extole.tokenStore:new f});
extole.define("https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/metric-registry.js",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/program.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ajax.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/token-store.js"],function(g,h,k){function l(c,e,b){b={metric_type:c,key:e,value:b};c={"Content-Type":"application/x-www-form-urlencoded",
"X-Extole-App":"javascript_sdk"};k.get()&&(c.Authorization="Bearer+"+k.get(),e=[g.getProtocol(),g.getProgramDomain(),"/api/v4/debug/metrics"].join(""),b=h.convertToFormUrlEncoded(c,b),h({url:e,type:"POST",headers:c,data:b,xhrFields:{withCredentials:!0}}))}function f(c){this.increment=function(e){l("COUNTER",c,e)}}function n(c){this.update=function(e){l("HISTOGRAM",c,e)}}return{histogram:function(c){return new n(c)},counter:function(c){return new f(c)}}});
extole.define("CreativeRenderContext",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js"],function(g,h){function k(f,c,e){this.getElement=function(){return e};this.getName=function(){return f};this.getData=function(){return c};this.getParameters=function(){return c}}function l(){this.getName=function(){return extole.PROGRAM.name};this.getProgramDomain=function(){return extole.PROGRAM.programDomain};
this.getSitePatterns=function(){return extole.PROGRAM.sitePatterns};this.getSiteRegexPatterns=function(){return extole.PROGRAM.siteRegexPatterns}}function f(){this.backendTargetingEnabled=function(){return!0};this.cookieConsentEnabled=function(){return extole.CORE_CONFIG.isCookieConsentEnabled}}return function(n,c,e,b){var a=new k(n,c,e),d=new l,m=new f;this.getZone=function(){return a};this.getProgram=function(){return d};this.getCreativeData=function(){var b=g.dotNotationToObject(g.deserialize(location.search)),
c=g.dotNotationToObject(a.getParameters());return h.merge(b.extole_creative,c.creative)};this.getCoreConfig=function(){return m};this.getLocale=function(){return b||null}}});
extole.define("find-element-by-id",["https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/metric-registry.js"],function(g,h){function k(g,f,h){function c(){if(f())h();else{g();var b=setTimeout;e||(e=10);var a=500<e?500:e*=1.1;b(c,a)}}var e;c()}return function(l,f){var n=(new Date).getTime(),c=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_NOT_FOUND||3E3,e=extole.MILLISECONDS_TO_WARN_WHEN_ELEMENT_FOUND||
2E3,b=!1,a;k(function(){a=document.getElementById(l)},function(){var d=(new Date).getTime()-n,f=!!a;f&&d>=e?(h.histogram("zone_element_found_slow").update(d),g.warn("EXTOLE_ELEMENT_FOUND_SLOW: Scan duration: "+d+"ms, element id: "+l)):!b&&d>=c&&(b=!0,h.histogram("zone_element_not_yet_found").update(d),g.warn("EXTOLE_ELEMENT_NOT_YET_FOUND: Scan duration: "+d+"ms, element id: "+l));return f},function(){f(a)})}});
extole.define("ensure-element",["find-element-by-id"],function(g){return function(h,k){h.element?k(h.element):h.element_id?g(h.element_id,k):k(document.body.appendChild(document.createElement("div")))}});
extole.define("pending-zone-service","https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/device-type.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/dom.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/type.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/metric-registry.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/token-store.js CreativeRenderContext ensure-element".split(" "),function(g,
h,k,l,f,n,c,e,b){function a(a,f){f=f||function(){};var g=a.name,k=m(a.data),l=Date.now();p(g);this.resolve=function(m,r,p,z){c.set(r,p);q(a)&&(r=d(g,"time_to_zone_response_ms"),p=Date.now()-l,n.histogram(r).update(p));b(a,function(b){a.element=b;q(a)&&w(a.element,function(){var a=d(g,"time_to_first_html_ms"),b=Date.now()-l;n.histogram(a).update(b)});h.clearEventListeners(a.element);b=new e(g,k,a.element,z);m(b);f(null,b.getZone())})}}function d(a,b){var c=document.getElementsByTagName("*").length;
c=2500<c?"xx_large":1500<c?"x_large":1E3<c?"large":500<c?"medium":"small";var d=g.isMobile((window.navigator||{}).userAgent)?"mobile":"desktop";return[a,d,c,b].join("_")}function m(a){a=f.merge({},a);delete a.campaign_id;delete a.extole_campaign_id;return a}function q(a){return u.test(a.name)||u.test((a.data||{}).redirect)?!0:!1}function w(a,b){var c=document.createElement("div");c.style.display="none";a.appendChild(c);v(c,b)}function v(a,b){if(window.MutationObserver){var c=new MutationObserver(function(d){f.each(d,
function(d){d.removedNodes&&f.each(d.removedNodes,function(d){d===a&&(b(),c.disconnect())})})});a.parentNode&&c.observe(a.parentNode,{childList:!0})}}var u=/_experience$/,t={},p=function(){var a={};return function(b){k.isUndefined(a[b])&&(a[b]=0);a[b]++;if(5===a[b]){b="duplicate_zone_requests : "+b;var c=f.filter(extole.q.history,function(a){return a.name&&"createZone"===a.name});c=f.map(c,function(a){delete (a.args[0]||{}).element;return a});l.warn(b,c)}}}();return{get:function(a){if(!t[a])throw Error("Pending zone does not exist for id: "+
a);return t[a]},create:function(){var b=Math.floor(1E9*Math.random()),c=0;return function(d,e){c++;var f=b+"."+c;t[f]=new a(d,e);return f}}()}});
extole.define("create-zone","extole-uri-parser https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/uri.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/collection.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/dom.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/program.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/client/token-store.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/ajax.js https://origin.xtlo.net/type=core:clientId=841133454:coreAssetsVersion=139/common/logger.js pending-zone-service".split(" "),function(g,
h,k,l,f,n,c,e,b){return function(a,d,m){function q(){r&&(p.jwt=r);y&&(p.access_token=y);A&&(p.debug="true");p.extole_app="javascript_sdk";u=[z,"/zones/",a.name].join("");var b=u+h.serialize(p),c=document.createElement("script");l.setAttribute(c,"src",b);l.setAttribute(c,"async","");l.append(l.queryFirst("head")||l.queryFirst("body"),c);c.onload=v}function w(){var b={"Content-Type":"application/x-www-form-urlencoded",Accept:"text/javascript","X-Extole-App":"javascript_sdk"};u=z+"/zones/"+a.name;r&&
(b["X-Extole-Jwt"]=r,delete p.jwt);y&&(b.Authorization="Bearer+"+y);A&&(b["X-Extole-Debug"]="true");var d=c.convertToFormUrlEncoded(b,p);c({url:u,type:"POST",headers:b,data:d,complete:function(a,b){var c=/^text\/html(;|$)/,f=/^text\/plain(;|$)/;b=b.getResponseHeader("Content-Type");if(/^text\/javascript(;|$)/.test(b))var g=a;else if(c.test(b))c=document.createElement("div"),c.innerHTML=a,g=l.queryFirst("script",c).innerHTML;else if(f.test(b)&&!a)e.info("No campaign targeted in POST to /zones - Zone Request Data: "+
d);else{if(null===b&&x<(extole.maxZoneRequestRetryCount||5)){x+=1;w();return}e.warn("Received "+b+" content type from "+u+"; Retry count: "+x+"; Zone Request Data: "+d)}if(g)try{(new Function(g))()}catch(B){e.error("Error in zone script retrieved from "+u+" - MESSAGE: "+B.message+" STACK: "+B.stack)}v()},error:function(a){e.error("Error creating zone via POST to "+u,a)},xhrFields:{withCredentials:!0}})}function v(){"function"===typeof m&&setTimeout(m,500)}d=d||function(){};var u,t=h.deserialize(location.search),
p=k.merge({},a.data||a.parameters),r=a.jwt||p.jwt||t.extole_jwt,y=n.get(),z=[f.getProtocol(),f.getProgramDomain()].join(""),A=p.debug&&"false"!==p.debug||extole.IS_DEBUG_ENABLED,x=0;extole.isPassRefererInZoneData&&(p.referer=location.href);extole.CORE_CONFIG.isGlobalZoneParametersEnabled&&(t=g.parseGlobalZoneParameters(t),p=k.merge(p,t));if(extole.createZonePrehandler&&(t=extole.createZonePrehandler(a,p),!1===t))return;a.element_id&&(p.element_id=a.element_id);a.data=p;p.zone_id=b.create(a,d);p=k.flatten(p);
extole.CORE_CONFIG.isZonePostEnabled?w():q()}});
extole.define("create-zone-executor",["create-zone","ensure-element"],function(g,h){function k(c,e){e=e||function(){};0===n?f.push(function(b){b=l(b);g(c,function(){var a=Array.prototype.slice.call(arguments);e.apply(null,a);b()},b)}):f.push(function(b){g(c,e);b()});n++}function l(c){var e=!1;return function(){var b=Array.prototype.slice.call(arguments);e||(e=!0,c.apply(null,b))}}var f=new function(){var c=0,e=[],b=this;this.push=function(a){e.push(a);this.next()};this.next=function(){function a(){c--;
b.next()}for(;1>c&&e.length;)e.shift()(a),c++}},n=0;return{initiateExecution:function(c,e){extole.isFindElementBeforeZoneRequest?h(c,function(b){c.element=b;k(c,e)}):k(c,e)}}});